apiVersion: v1
items:
- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    annotations:
      deprecated.daemonset.template.generation: "1"
      meta.helm.sh/release-name: consul
      meta.helm.sh/release-namespace: consul
    creationTimestamp: "2022-04-29T08:24:04Z"
    generation: 1
    labels:
      app: consul
      app.kubernetes.io/managed-by: Helm
      chart: consul-helm
      component: client
      heritage: Helm
      release: consul
    name: consul-client
    namespace: consul
    resourceVersion: "2217411"
    uid: 4a25f79c-9f98-4a7b-a7cb-572eb8e444c1
  spec:
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: consul
        chart: consul-helm
        component: client
        hasDNS: "true"
        release: consul
    template:
      metadata:
        annotations:
          consul.hashicorp.com/config-checksum: 562c2b5906ba811936ac9e01f783b867e5173a4ed4f33f22290928c89030da23
          consul.hashicorp.com/connect-inject: "false"
        creationTimestamp: null
        labels:
          app: consul
          chart: consul-helm
          component: client
          hasDNS: "true"
          release: consul
      spec:
        containers:
        - command:
          - /bin/sh
          - -ec
          - |
            CONSUL_FULLNAME="consul"

            mkdir -p /consul/extra-config
            cp /consul/config/extra-from-values.json /consul/extra-config/extra-from-values.json
            [ -n "${HOST_IP}" ] && sed -Ei "s|HOST_IP|${HOST_IP?}|g" /consul/extra-config/extra-from-values.json
            [ -n "${POD_IP}" ] && sed -Ei "s|POD_IP|${POD_IP?}|g" /consul/extra-config/extra-from-values.json
            [ -n "${HOSTNAME}" ] && sed -Ei "s|HOSTNAME|${HOSTNAME?}|g" /consul/extra-config/extra-from-values.json

            exec /usr/local/bin/docker-entrypoint.sh consul agent \
              -node="${NODE}" \
              -advertise="${ADVERTISE_IP}" \
              -bind=0.0.0.0 \
              -client=0.0.0.0 \
              -node-meta=host-ip:${HOST_IP} \
              -node-meta=pod-name:${HOSTNAME} \
              -hcl='leave_on_terminate = true' \
              -hcl='ca_file = "/consul/tls/ca/tls.crt"' \
              -hcl='auto_encrypt = {tls = true}' \
              -hcl="auto_encrypt = {ip_san = [\"$HOST_IP\",\"$POD_IP\"]}" \
              -hcl='verify_outgoing = true' \
              -hcl='ports { https = 8501 }' \
              -hcl='ports { http = -1 }' \
              -hcl='ports { grpc = 8502 }' \
              -config-dir=/consul/config \
              -datacenter=dc1 \
              -data-dir=/consul/data \
              -encrypt="${GOSSIP_KEY}" \
              -retry-join="${CONSUL_FULLNAME}-server-0.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc:8301" \
              -retry-join="${CONSUL_FULLNAME}-server-1.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc:8301" \
              -retry-join="${CONSUL_FULLNAME}-server-2.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc:8301" \
              -config-file=/consul/extra-config/extra-from-values.json \
              -domain=consul
          env:
          - name: ADVERTISE_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: NODE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: HOST_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: CONSUL_DISABLE_PERM_MGMT
            value: "true"
          - name: GOSSIP_KEY
            valueFrom:
              secretKeyRef:
                key: key
                name: consul-gossip-encryption-key
          - name: CONSUL_HTTP_ADDR
            value: https://localhost:8501
          - name: CONSUL_HTTP_SSL_VERIFY
            value: "false"
          image: hashicorp/consul:1.11.3
          imagePullPolicy: IfNotPresent
          name: consul
          ports:
          - containerPort: 8501
            hostPort: 8501
            name: https
            protocol: TCP
          - containerPort: 8502
            hostPort: 8502
            name: grpc
            protocol: TCP
          - containerPort: 8301
            name: serflan-tcp
            protocol: TCP
          - containerPort: 8301
            name: serflan-udp
            protocol: UDP
          - containerPort: 8600
            name: dns-tcp
            protocol: TCP
          - containerPort: 8600
            name: dns-udp
            protocol: UDP
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -ec
              - |
                curl \
                  -k \
                  https://127.0.0.1:8501/v1/status/leader \
                2>/dev/null | grep -E '".+"'
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /consul/data
            name: data
          - mountPath: /consul/config
            name: config
          - mountPath: /consul/tls/ca
            name: consul-ca-cert
            readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          fsGroup: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 100
        serviceAccount: consul-client
        serviceAccountName: consul-client
        terminationGracePeriodSeconds: 10
        volumes:
        - emptyDir: {}
          name: data
        - configMap:
            defaultMode: 420
            name: consul-client-config
          name: config
        - name: consul-ca-cert
          secret:
            defaultMode: 420
            items:
            - key: tls.crt
              path: tls.crt
            secretName: consul-ca-cert
    updateStrategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
      type: RollingUpdate
  status:
    currentNumberScheduled: 3
    desiredNumberScheduled: 3
    numberAvailable: 3
    numberMisscheduled: 0
    numberReady: 3
    observedGeneration: 1
    updatedNumberScheduled: 3
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
