apiVersion: v1
kind: ConfigMap
metadata:
 name: index-html-configmap
 namespace: demo
data:
 index.html: |
   <html>
   <h1>Welcome to Global Azure Demo</h1>
   </br>
   <h2>Hi! This is a configmap Index file </h2>
   <img src="https://globalazure.net/images/GlobalAzure2022-762.png" />
   </html
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo
  name: demo-svc
  namespace: demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo
  name: demo-deploy
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  strategy: {}
  template:
    metadata:
      labels:
        app: demo
    spec:
      volumes:
      - name: index
        configMap: 
          name: index-html-configmap
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: index
          mountPath: /usr/share/nginx/html/
        resources: {}
status: {}
