apiVersion: v1
kind: Service
metadata:
  labels:
    app: poideploy
  name: poideploy
  namespace: api
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: poideploy
status:
  loadBalancer: {}
