apiVersion: v1
kind: Service
metadata:
  labels:
    app: trips
  name: tripssvc
  namespace: api
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: trips
status:
  loadBalancer: {}
