apiVersion: v1
kind: Service
metadata:
  labels:
    app: tripsdeploy
  name: tripsdeploy
  namespace: api
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: tripsdeploy
status:
  loadBalancer: {}
