apiVersion: v1
kind: Service
metadata:
  labels:
    app: userprofile
  name: userprofilesvc
  namespace: api
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: userprofile
status:
  loadBalancer: {}
