apiVersion: v1
kind: Service
metadata:
  labels:
    app: userjava
  name: userjavasvc
  namespace: api
spec:
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: userjava
status:
  loadBalancer: {}
