apiVersion: v1
kind: Service
metadata:
  labels:
    app: userjavadeploy
  name: userjavadeploy
  namespace: api
spec:
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: userjavadeploy
status:
  loadBalancer: {}
