global:
  name: consul
  datacenter: dc1
  logLevel: info
  gossipEncryption:
    autoGenerate: true
#  metrics: 
#    enabled: true
#    enableAgentMetrics: true
#    agentMetricsRetentionTime: "1m"
#    enableGatewayMetrics: true
  tls:
    enabled: true
    enableAutoEncrypt: true
    verify: true
acls:
  manageSystemACLs: true
server:
  replicas: 3
  connect: true
  securityContext:
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
    fsGroup: 0
ui:
  enabled: true
  service:
    type: 'ClusterIP'
connectInject:
  enabled: true
  default: false
#  transparentProxy:
#    defaultEnabled: true
#    defaultOverwriteProbes: true
controller:
  enabled: true