#Pipeline name

name: 'dockerbuild_poi'


#Parameters for the pipeline

# CD Trigger

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - /containers_artifacts/src/poi/*

# Job Workers config

pool:
  vmImage: 'ubuntu-latest'

# Variables for the job

variables:
- group: CSILab
- group: CSILabKV

# Stages

stages:
  - stage: dockerbuild_poi
    jobs: 
    - job: dockerbuild
      continueOnError: false
      # Job step
      steps:
      - script: |
         echo '######################################################'   
         echo 'building container'
         echo '######################################################'
         echo
         docker version
         echo
         echo '######################################################'   
         echo 'Start Build'
         echo '######################################################'        
         docker build --no-cache \
         --build-arg IMAGE_VERSION="1.0" \
         --build-arg IMAGE_CREATE_DATE="`date \
         -u +"%Y-%m-%dT%H:%M:%SZ"`" \
         --build-arg IMAGE_SOURCE_REVISION="`git rev-parse HEAD`" -f Dockerfile -t "tripinsights/poi:1.0" .
         echo
         echo '######################################################'   
         echo 'Listing Docker image'
         echo '######################################################' 
         docker image ls
         echo
         echo '######################################################'   
         echo 'End Build'
         echo '######################################################' 

        workingDirectory: 'containers_artifacts/src/poi/'
        displayName: 'dockerbuild'
