#Pipeline name

name: 'dockerbuild_poi'


#Parameters for the pipeline

# CD Trigger

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - /containers_artifacts/src/poi/*

# Job Workers config

pool:
  vmImage: 'ubuntu-latest'

# Variables for the job

variables:
- group: CSILab
- group: CSILabKV

# Stages

stages:
  - stage: dockerbuild_poi
    jobs: 
    - job: dockerbuild
      continueOnError: false
      # Job step
      steps:
      - script: |
         echo '######################################################'   
         echo 'building container'
         echo '######################################################'
         echo
         docker version
        workingDirectory: '/containers_artifacts/src/poi/'
        displayName: 'dockerbuild'
