apiVersion: v1
kind: Service
metadata:
  labels:
    app: poi-consul
  name: poisvc-consul
  namespace: api-consul
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: poi-consul
status:
  loadBalancer: {}
