apiVersion: v1
kind: Service
metadata:
  labels:
    app: trips-consul
  name: tripssvc-consul
  namespace: tripsinsight-consul
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: trips-consul
status:
  loadBalancer: {}
