apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: userprofilegbl
    aadpodidbinding: uaicsitest2-binding
  name: userprofilegbl
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofilegbl
      aadpodidbinding: uaicsitest2-binding
  strategy: {}
  template:
    metadata:
      labels:
        app: userprofilegbl
        aadpodidbinding: uaicsitest2-binding
    spec:
      volumes:
      - name: sqlpwd
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: akvkv-ohtest
      containers:
      - image: acrbaqhp.azurecr.io/tripinsights/userprofile:1.0
        name: userprofile
        volumeMounts:
          - mountPath: /secrets
            name: sqlpwd
            readOnly: true
        env:
        - name: SQL_SERVER
          valueFrom:
            configMapKeyRef:
              name: userprofileconfigmap
              key: SQL_SERVER
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: userprofileconfigmap
              key: PORT
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: tripsecret
              key: SQL_USR        
        resources: {}
status: {}
