apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: akvkv-ohtest
  namespace: api
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"               
    userAssignedIdentityID: 42bcf026-c2f7-42e0-a325-396c043cf0fd
    keyvaultName: akvkv-subsetupconsul
    cloudName: ""                               
    objects:  |
      array:
        - |
          objectName: kvs-mssqladminpwd-consul
          objectAlias: SQL_PASSWORD            
          objectType: secret                    
          objectVersion:        
    tenantId: e0c45235-95fe-4bd6-96ca-2d529f0ebde4      